### PR TITLE
first release

### PR DESCRIPTION
**Pull request by jethror1**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1)* status: all files reviewed, 8 unresolved discussions (waiting on @jethror1)

___
*[dxapp.json, line 15 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1#-MJ_lsMw7CPgOVwlLq89:-MJ_lsMw7CPgOVwlLq8A:b-1dnneg) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/03c0a3852a260773f3b55803887d14e64bd6ebed/dxapp.json#L15)):*
> ```
> define
> ```
suggest we change this to 'specify'. We don't define the panel here, only specify which panel to use
___
*[dxapp.json, line 83 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1#-MJ_miru5_CLpIUHA3Eq:-MJ_miru5_CLpIUHA3Er:b-muxwji) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/03c0a3852a260773f3b55803887d14e64bd6ebed/dxapp.json#L83)):*
> ```
> sample id in as prefix
> ```
sample id as prefix
___
*[README.md, line 30 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1#-MJ_nkvzDxAW-QhiQ42c:-MJ_nkvzDxAW-QhiQ42d:b-cmul0r) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/03c0a3852a260773f3b55803887d14e64bd6ebed/README.md#L30)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
> AND also either:
> - the panel(s) and / or genes(s) to generate the bed for as a comma seperated string, with
>     genes being prefixed with an underscore (i.e. DDG2P, _CFTR)
> OR
> - bioinformatics manifest (from 001_References)
> AND
> - a sample identifying file (this is used to get the appropriate panel from the manifest for the sample,
>     this should be named X10000_ as the underscore is used to split and identify the sample). Any sample identifying file may be used (preferentially smaller to reduce download time).
> ```
</details>


is this
1 OR (2 AND 3)
or
(1 OR 2) AND 3
___
*[resources/home/dnanexus/generate_bed.py, line 77 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1#-MJ_puBRChXh54xuuRyI:-MJ_puBRChXh54xuuRyJ:b-oek3xf) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/03c0a3852a260773f3b55803887d14e64bd6ebed/resources/home/dnanexus/generate_bed.py#L77)):*
> ```
> low_memory=False
> ```
https://stackoverflow.com/questions/24251219/pandas-read-csv-low-memory-and-dtype-options
___
*[resources/home/dnanexus/generate_bed.py, line 146 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1#-MJ_rZ6e60eCWaMZlYZQ:-MJ_rZ6e60eCWaMZlYZR:b2c2hu3) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/03c0a3852a260773f3b55803887d14e64bd6ebed/resources/home/dnanexus/generate_bed.py#L146)):*
> ```
> g2t[g2t["gene"].isin(genes)]["transcript"].to_list()
> ```
Could you comment to explain what's going on here
___
*[src/eggd_generate_bed.sh, line 3 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1#-MJ_sYso4qhld6yBrjwI:-MJ_sYso4qhld6yBrjwJ:b38w5ln) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/03c0a3852a260773f3b55803887d14e64bd6ebed/src/eggd_generate_bed.sh#L3)):*
> ```Shell
> #!/bin/bash
> # eggd_generate_bed 1.0.0
> ```

set -euxo pipefail
___
*[src/eggd_generate_bed.sh, line 12 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1#-MJ_snLm8BkEb8I0tVe1:-MJ_snLm8BkEb8I0tVe2:b-nn25lf) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/03c0a3852a260773f3b55803887d14e64bd6ebed/src/eggd_generate_bed.sh#L12)):*
> ```
> echo "files"
> ```
Do we actually echo the files after echo "files"?
___
*[src/eggd_generate_bed.sh, line 32 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1#-MJ_swvx0d7YBxSxqVwg:-MJ_swvx0d7YBxSxqVwh:bodighv) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/03c0a3852a260773f3b55803887d14e64bd6ebed/src/eggd_generate_bed.sh#L32)):*
> ```
> pip3 install pandas==0.24.2
> ```
Can we include this in the app to remove the external dependency?

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1)* status: all files reviewed, 8 unresolved discussions (waiting on @mattgarner)

___
*[dxapp.json, line 15 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1#-MJ_lsMw7CPgOVwlLq89:-MJaTg7rEFzdWAsADRCL:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/03c0a3852a260773f3b55803887d14e64bd6ebed/dxapp.json#L15)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> define
> ```
suggest we change this to 'specify'. We don't define the panel here, only specify which panel to use
</blockquote></details>

Done.
___
*[dxapp.json, line 83 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1#-MJ_miru5_CLpIUHA3Eq:-MJaTgXCCusjveSN6hko:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/03c0a3852a260773f3b55803887d14e64bd6ebed/dxapp.json#L83)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> sample id in as prefix
> ```
sample id as prefix
</blockquote></details>

Done.
___
*[README.md, line 30 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1#-MJ_nkvzDxAW-QhiQ42c:-MJaU-15AypGd8AMm7B5:b-fk0sdi) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/03c0a3852a260773f3b55803887d14e64bd6ebed/README.md#L30)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> AND also either:
> - the panel(s) and / or genes(s) to generate the bed for as a comma seperated string, with
>     genes being prefixed with an underscore (i.e. DDG2P, _CFTR)
> OR
> - bioinformatics manifest (from 001_References)
> AND
> - a sample identifying file (this is used to get the appropriate panel from the manifest for the sample,
>     this should be named X10000_ as the underscore is used to split and identify the sample). Any sample identifying file may be used (preferentially smaller to reduce download time).
> ```

is this
1 OR (2 AND 3)
or
(1 OR 2) AND 3
</blockquote></details>

Should be 1 or (2 and 3), removed the and to make it clearer
___
*[resources/home/dnanexus/generate_bed.py, line 77 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1#-MJ_puBRChXh54xuuRyI:-MJaVErt0EeF6y1MbfM7:bxw3377) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/03c0a3852a260773f3b55803887d14e64bd6ebed/resources/home/dnanexus/generate_bed.py#L77)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> low_memory=False
> ```
https://stackoverflow.com/questions/24251219/pandas-read-csv-low-memory-and-dtype-options
</blockquote></details>

changed to used defined types
___
*[resources/home/dnanexus/generate_bed.py, line 146 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1#-MJ_rZ6e60eCWaMZlYZQ:-MJaVe_E6X_2-B7-CMSD:bhvdl46) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/03c0a3852a260773f3b55803887d14e64bd6ebed/resources/home/dnanexus/generate_bed.py#L146)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> g2t[g2t["gene"].isin(genes)]["transcript"].to_list()
> ```
Could you comment to explain what's going on here
</blockquote></details>

this matches all the genes in the panel against g2t and selects out the corresponding transcript for each to a list. Changed comment to make this clearer
___
*[src/eggd_generate_bed.sh, line 3 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1#-MJ_sYso4qhld6yBrjwI:-MJaX4rE0Q7wcqCJ-PrA:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/03c0a3852a260773f3b55803887d14e64bd6ebed/src/eggd_generate_bed.sh#L3)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

set -euxo pipefail
</blockquote></details>

Done.
___
*[src/eggd_generate_bed.sh, line 12 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1#-MJ_snLm8BkEb8I0tVe1:-MJaX66CCIWV1h_KTY0U:b-hfpv0l) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/03c0a3852a260773f3b55803887d14e64bd6ebed/src/eggd_generate_bed.sh#L12)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> echo "files"
> ```
Do we actually echo the files after echo "files"?
</blockquote></details>

removed
___
*[src/eggd_generate_bed.sh, line 32 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1#-MJ_swvx0d7YBxSxqVwg:-MJalIWq1QXW2WvZ1Qbg:biay5qq) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/03c0a3852a260773f3b55803887d14e64bd6ebed/src/eggd_generate_bed.sh#L32)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> pip3 install pandas==0.24.2
> ```
Can we include this in the app to remove the external dependency?
</blockquote></details>

changed to have a dir of require packages to install from, now has no external dependencies

**Review by mattgarner — APPROVED** [review]
> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1)* status: all files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[app_file_ids.json, line 4 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1#-MJasXuxCA1AKM8D1nGi:-MJasXuxCA1AKM8D1nGj:b-cpq91j) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/a6f9cf7e5daf9e7590e490a6ee0a5d457eaceddb/app_file_ids.json#L4)):*
<details><summary><i alt="summary">Quoted 14 lines of code…</i></summary>

> ```
> {
>         "manifest": {
>             "$dnanexus_link": "file-FvyX44j433Gz74z60Vg0QgkG"
>         },
>         "exons_nirvana": {
>             "$dnanexus_link": "file-Fq18Yp0433GjB7172630p9Yv"
>         },
>         "nirvana_genes2transcripts": {
>             "$dnanexus_link": "file-FxkXQGQ433GVfVzJGqKq039y"
>         },
>         "gemini_panels": {
>             "$dnanexus_link": "file-Fq3yY48433GxY9VQ9ZZ9ZfqX"
>         }
> }
> ```
</details>

Unused file?
___
*[resources/home/dnanexus/generate_bed.py, line 85 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1#-MJauR6G7v1elDDi7wFU:-MJauR6G7v1elDDi7wFV:b-gm2qa1) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/03c0a3852a260773f3b55803887d14e64bd6ebed/resources/home/dnanexus/generate_bed.py#L85)):*
> ```
>     else:
>         build38 = False
> ```
what if "39" in args.exons_nirvana but "37" not. 
Fine for now, but would be good to raise an issue to document this 
___
*[src/eggd_generate_bed.sh, line 13 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1#-MJatqYUAxjpvx-RBgaW:-MJatqYUAxjpvx-RBgaX:b2062ra) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/03c0a3852a260773f3b55803887d14e64bd6ebed/src/eggd_generate_bed.sh#L13)):*
> ```
> ls
> ```
I feel bad for having missed this the first time!

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1)* status: all files reviewed, 3 unresolved discussions (waiting on @jethror1)

**Review by mattgarner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1)* status: all files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[app_file_ids.json, line 4 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1#-MJasXuxCA1AKM8D1nGi:-MJavbv-8ixiEejx3Byk:b32w0x) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/a6f9cf7e5daf9e7590e490a6ee0a5d457eaceddb/app_file_ids.json#L4)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> {
>         "manifest": {
>             "$dnanexus_link": "file-FvyX44j433Gz74z60Vg0QgkG"
>         },
>         "exons_nirvana": {
>             "$dnanexus_link": "file-Fq18Yp0433GjB7172630p9Yv"
>         },
>         "nirvana_genes2transcripts": {
>             "$dnanexus_link": "file-FxkXQGQ433GVfVzJGqKq039y"
>         },
>         "gemini_panels": {
>             "$dnanexus_link": "file-Fq3yY48433GxY9VQ9ZZ9ZfqX"
>         }
> }
> ```
Unused file?
</blockquote></details>

OK

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1)* status: all files reviewed, 1 unresolved discussion (waiting on @mattgarner)

___
*[resources/home/dnanexus/generate_bed.py, line 85 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1#-MJauR6G7v1elDDi7wFU:-MJawE79Dubn9ybrhMp5:b263wpy) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/03c0a3852a260773f3b55803887d14e64bd6ebed/resources/home/dnanexus/generate_bed.py#L85)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>     else:
>         build38 = False
> ```
what if "39" in args.exons_nirvana but "37" not. 
Fine for now, but would be good to raise an issue to document this 
</blockquote></details>

True, will probably we a long time away but shall have a think how to handle this for next release
___
*[src/eggd_generate_bed.sh, line 13 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1#-MJatqYUAxjpvx-RBgaW:-MJawM73DvMDK7q_Sz6D:b-japldm) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/03c0a3852a260773f3b55803887d14e64bd6ebed/src/eggd_generate_bed.sh#L13)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> ls
> ```
I feel bad for having missed this the first time!
</blockquote></details>

Didn't actually mean to leave the echos in either

**Review by mattgarner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/1#-:-MJaxAwg18fvBGj9ueY4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
