### PR TITLE
v1.2.0 - handle adding custom regions

### PR DESCRIPTION
**Pull request by sophie22**
Optional input tsv with 7 columns: chromosome, start, end, gene symbol, transcript (custom string), exon number (or other numeric label), HGNC gene ID or clinical indication
If provided, additional regions will be added to the bed file based on the gene(s) or clinical indication in the last column.

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16)* status: 6 of 10 files reviewed, 9 unresolved discussions (waiting on @jethror1 and @sophie22)

___
*[README.md, line 31 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16#-N-cop6rDazdcydeeXIJ:-N-cop6rDazdcydeeXIK:b-3xgmf0) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/af6c9df0aa60220297591dc4cb6b4b450c172d12/README.md#L31)):*
> ```Markdown
>     this should be named X10000_ as the underscore is used to split and identify the sample). Any sample identifying file may be used (preferentially smaller to reduce download time).
> 
> Optionally, additional regions may be provided for a gene or panel.
> ```

can you add a bit more here about the format and usage of this, i.e. that the file requires as a minimum `chrom start end transcript` and can have more columns that will be ignored
___
*[resources/home/dnanexus/generate_bed.py, line 7 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16#-N-cljeNC0gAy8s_8GAd:-N-cljeNC0gAy8s_8GAe:bgtf55p) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/af6c9df0aa60220297591dc4cb6b4b450c172d12/resources/home/dnanexus/generate_bed.py#L7)):*
> ```Python
> Jethro Rainford
> 200928
> last modified: 220414 Sophie Ratkai
> ```

can this be removed? Not really needed since everything is in github and commits show when it was last changed and by who



_Code quote:_
```Python

200928
last modified: 220414 Sophie Ratkai
```
___
*[resources/home/dnanexus/generate_bed.py, line 111 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16#-N-cm4-S59-u_SzS00Mg:-N-cm4-S59-u_SzS00Mh:bjwckl3) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/af6c9df0aa60220297591dc4cb6b4b450c172d12/resources/home/dnanexus/generate_bed.py#L111)):*
> ```Python
>         )
> 
>     if args.additional_regions is not None:
> ```

this can just be `if args.additional_regions:`, if an argument is not specified then it will be set to `None` in the argparse NameSpace
___
*[resources/home/dnanexus/generate_bed.py, line 115 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16#-N-cmXkH7DqdVUqq4GBn:-N-cmXkI0SuK889zYucN:b-7wmpnc) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/af6c9df0aa60220297591dc4cb6b4b450c172d12/resources/home/dnanexus/generate_bed.py#L115)):*
> ```Python
>             additional_regions = pd.read_csv(
>                 extra_regions, sep="\t",
>                 names=["chromosome", "start", "end", "gene", "transcript",
> ```

can these be inferred from the file header so that it doesn't break if we change the file format
___
*[resources/home/dnanexus/generate_bed.py, line 117 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16#-N-cmmTR-7-zAX4QHAzn:-N-cmmTR-7-zAX4QHAzo:b6t583) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/af6c9df0aa60220297591dc4cb6b4b450c172d12/resources/home/dnanexus/generate_bed.py#L117)):*
> ```Python
>                 names=["chromosome", "start", "end", "gene", "transcript",
>                         "exon", "gene_panel"],
>                 dtype={
> ```

for a tiny file it's not really necessary to set dtypes, and I'd be careful with things like exon being an int if you ever want to store something different there for intronic or upstream / downstream regions.

also fyi pandas has a built in method you can use for setting the most appropriate dtypes: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.convert_dtypes.html
___
*[resources/home/dnanexus/generate_bed.py, line 122 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16#-N-cmOw62vTk-Dw8sHwo:-N-cmOw79OQ3oIwiNKkB:b-83xzpf) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/af6c9df0aa60220297591dc4cb6b4b450c172d12/resources/home/dnanexus/generate_bed.py#L122)):*
> ```Python
>                 }
>             )
>     else:
> ```

is this an empty df? why? If it is just to amek it optional further down I'd set it to `None`
___
*[resources/home/dnanexus/generate_bed.py, line 179 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16#-N-cne4MEK31tx9DGX08:-N-cne4MEK31tx9DGX09:bg6z84o) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/af6c9df0aa60220297591dc4cb6b4b450c172d12/resources/home/dnanexus/generate_bed.py#L179)):*
> ```Python
>         else:
>             # panel
>             genes.extend(gene_panels.loc[
> ```

what's changed here? 
___
*[resources/home/dnanexus/generate_bed.py, line 202 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16#-N-coEbm-cc5Q9Ee412R:-N-coEbm-cc5Q9Ee412S:bq0v7x9) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/af6c9df0aa60220297591dc4cb6b4b450c172d12/resources/home/dnanexus/generate_bed.py#L202)):*
> ```Python
> 
>     # get exons from exons_nirvana for transcripts
>     exons = exons_nirvana.loc[exons_nirvana["transcript"].isin(transcripts),
> ```

is this all for additional regions? setting it to None if not being used then having `if additional_regions:` again here would be clearer that this is only being used when additional regions file is passed



_Code quote:_
```Python
a
```
___
*[resources/home/dnanexus/generate_bed.py, line 254 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16#-N-coYD65ukT60LOO02M:-N-coYD65ukT60LOO02N:b-bwiq71) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/af6c9df0aa60220297591dc4cb6b4b450c172d12/resources/home/dnanexus/generate_bed.py#L254)):*
> ```Python
> def main():
>     """
>         Main function to generate bed file.
> ```

remove indent

**Review by sophie22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16)* status: 6 of 10 files reviewed, 10 unresolved discussions (waiting on @jethror1)

___
*[README.md, line 31 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16#-N-cop6rDazdcydeeXIJ:-N-d1Pxz7-nQm4u6xGcL:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/af6c9df0aa60220297591dc4cb6b4b450c172d12/README.md#L31)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can you add a bit more here about the format and usage of this, i.e. that the file requires as a minimum `chrom start end transcript` and can have more columns that will be ignored
</blockquote></details>

Done.
___
*[resources/home/dnanexus/generate_bed.py, line 7 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16#-N-cljeNC0gAy8s_8GAd:-N-d1RaP4tQuaevlagUG:b-hfpv0l) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/af6c9df0aa60220297591dc4cb6b4b450c172d12/resources/home/dnanexus/generate_bed.py#L7)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can this be removed? Not really needed since everything is in github and commits show when it was last changed and by who
</blockquote></details>

removed
___
*[resources/home/dnanexus/generate_bed.py, line 111 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16#-N-cm4-S59-u_SzS00Mg:-N-d1Vw5DEXbzITi7p2B:b-yigp24) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/af6c9df0aa60220297591dc4cb6b4b450c172d12/resources/home/dnanexus/generate_bed.py#L111)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this can just be `if args.additional_regions:`, if an argument is not specified then it will be set to `None` in the argparse NameSpace
</blockquote></details>

corrected
___
*[resources/home/dnanexus/generate_bed.py, line 115 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16#-N-cmXkH7DqdVUqq4GBn:-N-czsceBpNb-ls8GmOM:b1h4gaw) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/af6c9df0aa60220297591dc4cb6b4b450c172d12/resources/home/dnanexus/generate_bed.py#L115)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can these be inferred from the file header so that it doesn't break if we change the file format
</blockquote></details>

could, the current file has no header
___
*[resources/home/dnanexus/generate_bed.py, line 117 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16#-N-cmmTR-7-zAX4QHAzn:-N-d1gfjCbyI688FIhjK:b-ca0z3f) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/af6c9df0aa60220297591dc4cb6b4b450c172d12/resources/home/dnanexus/generate_bed.py#L117)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

for a tiny file it's not really necessary to set dtypes, and I'd be careful with things like exon being an int if you ever want to store something different there for intronic or upstream / downstream regions.

also fyi pandas has a built in method you can use for setting the most appropriate dtypes: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.convert_dtypes.html
</blockquote></details>

I followed what was there for other files
___
*[resources/home/dnanexus/generate_bed.py, line 122 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16#-N-cmOw62vTk-Dw8sHwo:-N-d1kDJ5tcJLai3aoCC:b-50js3g) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/af6c9df0aa60220297591dc4cb6b4b450c172d12/resources/home/dnanexus/generate_bed.py#L122)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

is this an empty df? why? If it is just to amek it optional further down I'd set it to `None`
</blockquote></details>

makes sense, corrected it
___
*[resources/home/dnanexus/generate_bed.py, line 179 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16#-N-cne4MEK31tx9DGX08:-N-d-6bDBVbH_KaxvT5d:b9bo1qw) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/af6c9df0aa60220297591dc4cb6b4b450c172d12/resources/home/dnanexus/generate_bed.py#L179)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

what's changed here? 
</blockquote></details>

added the comment line # panel and change where the line break is
___
*[resources/home/dnanexus/generate_bed.py, line 194 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16#-N-d1x0P0V4rHkpXmZrF:-N-d1x0P0V4rHkpXmZrG:bh43do0) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/af6c9df0aa60220297591dc4cb6b4b450c172d12/resources/home/dnanexus/generate_bed.py#L194)):*
> ```Python
>     transcripts = g2t.loc[(g2t["gene"].isin(genes)) &
>                         (g2t["clinical_tx"] == "clinical_transcript"),
>                         "transcript"].unique().tolist()
> ```

using pandas.Series.unique.tolist instead of list(set(list))
___
*[resources/home/dnanexus/generate_bed.py, line 202 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16#-N-coEbm-cc5Q9Ee412R:-N-d25UB7HT3Fuef5pb5:b-knp4ur) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/af6c9df0aa60220297591dc4cb6b4b450c172d12/resources/home/dnanexus/generate_bed.py#L202)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

is this all for additional regions? setting it to None if not being used then having `if additional_regions:` again here would be clearer that this is only being used when additional regions file is passed
</blockquote></details>

changed, is it better?
___
*[resources/home/dnanexus/generate_bed.py, line 254 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16#-N-coYD65ukT60LOO02M:-N-d27rb1JM0WTUZr2Hk:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/af6c9df0aa60220297591dc4cb6b4b450c172d12/resources/home/dnanexus/generate_bed.py#L254)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

remove indent
</blockquote></details>

Done.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r1, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @jethror1 and @sophie22)

___
*[resources/home/dnanexus/generate_bed.py, line 115 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16#-N-cmXkH7DqdVUqq4GBn:-N005csy-7AQSuc8i9fS:b-wvtqat) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/af6c9df0aa60220297591dc4cb6b4b450c172d12/resources/home/dnanexus/generate_bed.py#L115)):*
<details><summary><i>Previously, sophie22 wrote…</i></summary><blockquote>

could, the current file has no header
</blockquote></details>

can you change it 
___
*[resources/home/dnanexus/generate_bed.py, line 117 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16#-N-cmmTR-7-zAX4QHAzn:-N008PK955Ttp6gQRfF4:b-nyoh2l) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/af6c9df0aa60220297591dc4cb6b4b450c172d12/resources/home/dnanexus/generate_bed.py#L117)):*
<details><summary><i>Previously, sophie22 wrote…</i></summary><blockquote>

I followed what was there for other files
</blockquote></details>

do you think you would want exon to be something else other than an int? If so I'd remove it and let it set it automatically
___
*[resources/home/dnanexus/generate_bed.py, line 194 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16#-N-d1x0P0V4rHkpXmZrF:-N006nDKDHPeNjZqEVWN:b-j23wkp) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/af6c9df0aa60220297591dc4cb6b4b450c172d12/resources/home/dnanexus/generate_bed.py#L194)):*
<details><summary><i>Previously, sophie22 wrote…</i></summary><blockquote>

using pandas.Series.unique.tolist instead of list(set(list))
</blockquote></details>

can this be switched to format something like this to fix the pep8 issue, also having your new lines indented by just one tab can be better for managing line length instead of starting further out
```
transcripts = g2t.loc[
        (g2t["gene"].isin(genes)) &
        (g2t["clinical_tx"] == "clinical_transcript"), "transcript"
    ].unique().tolist()
```



_Code quote:_
```Python
    transcripts = g2t.loc[(g2t["gene"].isin(genes)) &
                        (g2t["clinical_tx"] == "clinical_transcript"),
                        "transcript"].unique().tolist()
```

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @jethror1 and @sophie22)

___
*[resources/home/dnanexus/generate_bed.py, line 115 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16#-N-cmXkH7DqdVUqq4GBn:-N00A42j1QFohwWA6Ydn:b19v7am) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/af6c9df0aa60220297591dc4cb6b4b450c172d12/resources/home/dnanexus/generate_bed.py#L115)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can you change it 
</blockquote></details>

feel like I meant to finish off this sentence but I forgot what I was going to say so ignore me, you added to the readme what it needs

**Review by sophie22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16)* status: 8 of 10 files reviewed, all discussions resolved (waiting on @jethror1)

___
*[resources/home/dnanexus/generate_bed.py, line 115 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16#-N-cmXkH7DqdVUqq4GBn:-N00T5d98g6PwcF4I-mO:bqvfxp3) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/af6c9df0aa60220297591dc4cb6b4b450c172d12/resources/home/dnanexus/generate_bed.py#L115)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

feel like I meant to finish off this sentence but I forgot what I was going to say so ignore me, you added to the readme what it needs
</blockquote></details>

changed so that column headers are inferred and presence of required columns is asserted

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @jethror1)

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sophie22)

**Pull request merged**
